export enum PingerAccount {
  MEDIANIZER_ETH = 0,
  MEDIANIZER_RAI = 1,
  FSM_ETH = 2,
  RATE_SETTER = 3,
  TAX_COLLECTOR = 4,
  PAUSE_EXECUTOR = 5,
  MEDIANIZER_FLX = 6,
  FSM_FLX = 7,
  STABILITY_FEE_TREASURY = 8,
  ACCOUNTING_ENGINE = 9,
  MEDIANIZER_RAI_SPOT = 10,
  MISCELLANEOUS = 11,
}
